Draft: Feature/add description to feature toggles
nusje2000/feature-toggle-bundle pull request #51
Opened 2022-06-02 16:57 UTC by KevinVanSonsbeek

- [x] Add methods to the Feature interface
- [x] Add description to the Create and Update controllers
- [x] Make the View controller return the description
- [x] Add description to the FeatureMapper 
- [ ] Allow  proposed config options to be succesfully parsed

Proposed config options:
```yaml
nusje2000_feature_toggle:
    environment:
        features:
            feature_toggle_1: true
            feature_toggle_2: false
            feature_toggle_3:
                description: 'For human. By human.'
                value: false
```

2022-06-07 07:55 UTC, nusje2000 requested changes

2022-06-07 07:55 UTC, nusje2000 commented on src/DependencyInjection/Nusje2000FeatureToggleExtension.php
> +     *          value: bool,
I would suggest using the name "state"

2022-06-07 07:55 UTC, nusje2000 commented on tests/Unit/Controller/Host/Feature/UpdateControllerTest.php
> +
Can you add a `testInvokeWithDescriptionOnly`?

2022-06-07 17:47 UTC, KevinVanSonsbeek commented on src/Controller/Host/Feature/UpdateController.php
> +        $description = $json['description'] ?? null;
What would be more preferable behavior, checking if the key exists, if it does, check the type, and update it if it's not the same? Or explicitly pass false to description to clear it?

2022-06-07 18:08 UTC, nusje2000 commented on src/Controller/Host/Feature/UpdateController.php
> +        $description = $json['description'] ?? null;
I would suggest using an array_key_exists

2022-06-07 18:08 UTC, nusje2000 commented on src/DependencyInjection/Nusje2000FeatureToggleExtension.php
> +     *          value: bool,
That would be a better option indeed 👍

2022-06-08 16:52 UTC, KevinVanSonsbeek commented on tests/Unit/Controller/Host/Feature/UpdateControllerTest.php
> +
I've refactored the test to be based on a data provider, so more test cases can be added at ease.

2022-06-08 16:53 UTC, KevinVanSonsbeek commented on src/DependencyInjection/Nusje2000FeatureToggleExtension.php
> +     *          value: bool,
The option has been renamed from "value" to "enabled"

2022-07-01 10:13 UTC, merged