Bugfix/#51 fix description not being set with remote feature repository
nusje2000/feature-toggle-bundle pull request #54
Opened 2022-09-05 17:41 UTC by KevinVanSonsbeek

Fixes #53

2022-09-07 15:57 UTC, KevinVanSonsbeek commented
Do you have time to review these fixes? @nusje2000

2022-09-07 16:23 UTC, nusje2000 requested changes

2022-09-07 16:23 UTC, nusje2000 commented on src/DependencyInjection/Configuration.php
>  }
Since the arguments are not conditional anymore, we can add them to the call directly.

2022-09-07 16:24 UTC, nusje2000 commented
@KevinVanSonsbeek one minor change request, but looks good 👍

2022-09-08 17:11 UTC, KevinVanSonsbeek commented on src/DependencyInjection/Configuration.php
>  }
I've added them directly to the call now.

2022-09-16 06:45 UTC, KevinVanSonsbeek commented
> @KevinVanSonsbeek one minor change request, but looks good +1

Would you have time to re-review the PR?

2022-09-26 06:44 UTC, KevinVanSonsbeek commented
Would you have time to re-review this MR in the coming week? @nusje2000

2022-09-26 10:57 UTC, merged

2022-09-26 10:57 UTC, nusje2000 commented
Thanks for your work @KevinVanSonsbeek 🚀🚀🚀

2022-09-26 11:42 UTC, KevinVanSonsbeek commented
Could you make a 4.0.1 tag for this fix? @nusje2000

2022-09-26 11:45 UTC, nusje2000 commented
@KevinVanSonsbeek https://github.com/nusje2000/feature-toggle-bundle/releases/tag/v4.0.1