Feature/#59 Remove myclabs enum
nusje2000/feature-toggle-bundle pull request #62
Opened 2024-05-21 20:19 UTC by KevinVanSonsbeek

Converted the State to a native enum and removed the dependency on the `myclabs/php-enum` package.

Additionally also extended the jobs to run on php 8.3, and run the tests and code analysis on the lowest "supported" dependencies as well. (As i found out that the myclabs package actually needed atleast version 1.7 to work)

2024-05-21 20:23 UTC, KevinVanSonsbeek commented
@nusje2000 the failed job is related to the pipeline not being able to install psalm. But i do not seem to have an option to rerun it.

2024-05-22 06:59 UTC, nusje2000 requested changes
Looks great! One small change request, but thats all. Great work :rocket: :rocket:

2024-05-22 06:59 UTC, nusje2000 commented on .github/workflows/build.yml
>      tests:
**Suggestion:** Instead of defining the code_analysis twice, where one has the additional `lowest` dependency versions, you should be able to include this within the matrix. I'm not enterly sure how, but I think something like this:

```yaml
        strategy:
            matrix:
                php-versions: [ '8.1', '8.2', '8.3' ]
                dependency-version: ['lowest', 'highest']
```

Then during composer install you can pass the parameter from the matrix:

```yaml
          -   uses: ramsey/composer-install@v1
              with:
                  dependency-versions: ${{ matrix-dependency-version }}
```

Same can be done for the static analysis

2024-05-22 07:01 UTC, nusje2000 commented on .github/workflows/build.yml
> +    code_analysis_lowest_dependencies:
**Praise:** Never thought of using the lowest dependencies here, such an awesome addition!

2024-05-22 15:41 UTC, KevinVanSonsbeek commented on .github/workflows/build.yml
>      tests:
Added the dependency version to the matrix as well. Works nicely as intended 😄

2024-05-23 06:04 UTC, KevinVanSonsbeek commented on .github/workflows/build.yml
> +                    dependency-versions: lowest
```suggestion
                    dependency-versions: ${{ matrix.dependency-version }}
```

2024-05-23 06:04 UTC, KevinVanSonsbeek commented on .github/workflows/build.yml
> +                    dependency-versions: lowest
```suggestion
                    dependency-versions: ${{ matrix.dependency-version }}
```

2024-05-27 20:41 UTC, nusje2000 approved these changes

2024-05-27 20:41 UTC, merged